"""changes

Revision ID: ee1813d11a42
Revises: 499b1c0b4a73
Create Date: 2021-11-20 14:05:07.867011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1813d11a42'
down_revision = '499b1c0b4a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'price')
    # ### end Alembic commands ###
