"""hiii

Revision ID: f7b79b9ff145
Revises: 1de08e000c34
Create Date: 2021-11-20 20:45:00.151306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b79b9ff145'
down_revision = '1de08e000c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_daily_value')
    # ### end Alembic commands ###
